skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_program = "4Y55LTgKQPYsy9pTqXYUupeRrogBDG83LwJTmWEkggfh"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
