skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
horkos = "8aYmwr4ypua4cmwfRUZQ72JHEm4qpUUTRUPgTDCh5RU3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
